import Navbar from "@/components/navbar";
import { Box, Flex} from "@chakra-ui/react";
import React, {useEffect, useState} from "react";
import axios from "axios";
import Link from "next/link";
import Head from "next/head";

export default function Home() {
  const [todos, setTodos] = useState([]);

    useEffect(() => {
        fetchTodos();
    }, []);

    const fetchTodos = async () => {
        try{
            const token = localStorage.getItem('token');
            const response = await axios.get('http://localhost:3001/api/todo', {
              headers: {
                Authorization: `Bearer ${token}`
              }
            });
            setTodos(response.data);
        }catch(err){
            console.error('Error fetching users:', err);
        }
    };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
            <Flex w='100%' h='100vh' alignItems='center' justifyContent='center' wrap='wrap'>
                {todos.map((todo) => (
                  <Box w='200px' h='200px' bgColor='transparent' border='7px' borderStyle='solid' borderColor='#E8947E' rounded='xl' mx='5'>
                    <div key={todo.id}>
                        <Link href={`/todo/${todo.id}`}>
                                {todo.title}</Link>
                    </div>
                  </Box>
                ))}
                
            </Flex>
    </>
  );
}
